import Head from "next/head";
import ListView from "../pages/employees/list";

export default function Home() {
	return (
		<>
			<Head>
				<title>Employee manager</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<ListView />
		</>
	);
} //end of the homepage.
